### ISSUE TITLE
Conbee II not found

### ISSUE THREAD

**Issue by svaarala** [WebThingsIO/zigbee-adapter#121]
I ordered a Conbee II recently and tried to use it with Mozilla WebThings Gateway running on a Raspberry PI. The adapter is found but this shows up in the WebThings log:

```
2019-05-15 21:40:34.768 INFO   : Loading add-on: zigbee-adapter
2019-05-15 21:40:35.455 INFO   : zigbee: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-05-15 21:40:35.495 INFO   : zigbee: Loading add-on for zigbee-adapter from /home/pi/.mozilla-iot/addons/zigbee-adapter
2019-05-15 21:40:36.068 INFO   : zigbee: DEBUG config = ''
2019-05-15 21:40:36.314 INFO   : zigbee: Serial ports that were found:
2019-05-15 21:40:36.501 INFO   : zigbee: Serial Device found @ /dev/ttyAMA0
2019-05-15 21:40:36.507 INFO   : zigbee: Serial Device found @ /dev/ttyS0
2019-05-15 21:40:36.509 INFO   : zigbee: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE1964169 found @ /dev/ttyACM0
2019-05-15 21:40:36.511 ERROR  : zigbee: Failed to load zigbee-adapter - No Zigbee dongle found
2019-05-15 21:40:36.923 INFO   : Plugin: zigbee-adapter died, code = 100 NOT restarting...
```

I looked through the issues related to "dongle not found" but it appears Conbee II should be supported hardware and should work out of the box.

I checked that the adapter works fine through deCONZ, and can communicate with one of my Philips Hue lights, so the hardware appears functional.

**Comment by dhylands** [comment]
I think that VID:PID changed and I'll need to make a tweak to the zigbee adapter.

**Comment by svaarala** [comment]
Let me know if I can help in providing dumps or testing the change :+1:

**Comment by joris-** [comment]
Hi !
Same problem, discourse posts : https://discourse.mozilla.org/t/zigbee-failed-to-load-zigbee-adapter-no-zigbee-dongle-found/40429 & https://discourse.mozilla.org/t/conbee-ii-support/38792/13

I've tried to had VID/PID in `filter` to `xBeeSerialProber` and this line get removed ⬇️ 
> 2019-05-15 21:40:36.509 INFO   : zigbee: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE1964169 found @ /dev/ttyACM0

It looks like the `serialPortMatchesFilter` function from `serial-prober.js` of [serial-prober-node](https://github.com/mozilla-iot/serial-prober-node) return `false` and don't know why at this moment

**Comment by dhylands** [comment]
Version 0.7.7 of the zigbee-adapter should now support the ConBee II. I've only done limited testing so I'd appreciate hearing about any issues.

**Comment by svaarala** [comment]
Thanks! Updated the Zigbee adapter and I can now discover and control lights as expected, with no issues so far.

**Comment by svaarala** [comment]
The adapter worked for a while and I was able to pair a few devices. But now it suddenly stopped working - I'm not sure whether the issue is with the gateway itself or the adapter, but maybe this log provides a clue:
```
2019-05-23 21:00:26.066 INFO   : Loading add-on: zigbee-adapter
2019-05-23 21:00:26.761 INFO   : zigbee: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-05-23 21:00:26.803 INFO   : zigbee: Loading add-on for zigbee-adapter from /home/pi/.mozilla-iot/addons/zigbee-adapter
2019-05-23 21:00:27.432 INFO   : zigbee: DEBUG config = ''
2019-05-23 21:00:28.226 ERROR  : zigbee: Failed to load zigbee-adapter - Error: Port /dev/ttyACM0 looks like it might be a/an deConz dongle, but it couldn't be opened. SerialProber: timeout: deConz dongle not detected on /dev/ttyACM0
2019-05-23 21:00:28.228 ERROR  : zigbee:     at Function.probeAll (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/serial-prober/serial-prober.js:157:19)
2019-05-23 21:00:28.230 ERROR  : zigbee:     at <anonymous>
2019-05-23 21:00:28.232 INFO   : zigbee: Unhandled Rejection
2019-05-23 21:00:28.235 ERROR  : zigbee: { Error: Canceled
2019-05-23 21:00:28.236 ERROR  : zigbee:     at Poller.emitCanceled (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/bindings/lib/poller.js:101:17)
2019-05-23 21:00:28.237 ERROR  : zigbee:     at Poller.stop (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/bindings/lib/poller.js:91:10)
2019-05-23 21:00:28.238 ERROR  : zigbee:     at close.then (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/bindings/lib/linux.js:48:19)
2019-05-23 21:00:28.240 ERROR  : zigbee:     at <anonymous> canceled: true }
2019-05-23 21:00:28.639 INFO   : Plugin: zigbee-adapter died, code = 100 NOT restarting...
```

**Comment by svaarala** [comment]
Prior to this the adapter worked to some extent (it seemed to be unreliable with an Ikea Trådfri on/off switch):
```
2019-05-23 20:48:01.734 INFO   : Successfully created new thing zb-000d6ffffead908b-multiLevelSwitch
2019-05-23 20:48:07.472 INFO   : zigbee: Frame Status: 0: SUCCESS
2019-05-23 20:48:07.486 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:48:07.493 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:48:07.595 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:48:09.245 INFO   : zigbee: setProperty property: on for: zb-000d6ffffead908b-multiLevelSwitch profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 20:48:27.513 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:48:27.636 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:48:47.535 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:49:07.551 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:49:07.675 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:49:27.569 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:49:27.696 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 20:49:38.654 INFO   : zigbee: setProperty property: on for: zb-000d6ffffead908b-multiLevelSwitch profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 20:49:44.236 INFO   : zigbee: setProperty property: on for: zb-000d6ffffead908b-multiLevelSwitch profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 20:49:44.816 INFO   : zigbee: setProperty property: on for: zb-000d6ffffead908b-multiLevelSwitch profileId: 0104 endpoint: 1 clusterId: 0006 zcl: off value: false
[...]
```

A while after this, I wasn't able to control any devices.

**Comment by sarimner** [comment]
Good work!
Thanks
I can now find atleast two things now
The aqara temp and humidity sensor is working but i cannot switch the Ikea trådfri power plug
Maybe it is another issue than the gateway adapter addon.
/ Per

**Comment by dhylands** [comment]
I ran into the problem of not being able to open the ConBee port a few times and I haven't figured out what the issue is yet. Usually, if I waited a few minutes and tried again then it would open fine.

The ROUTE_DISCOVERY messages are normal with battery powered devices.

I have an Ikea Trafri on/off switch, so I'll make sure to test that as well.

**Comment by svaarala** [comment]
After a few reboots the behavior seems to repeat, first everything looks good:
```
2019-05-23 21:14:03.361 INFO   : zigbee: this.driver = DeconzDriver {}
2019-05-23 21:14:03.364 INFO   : zigbee: DeconzDriver: Using serial port /dev/ttyACM0
2019-05-23 21:14:03.384 INFO   : zigbee: DeConz Firmware version: 26420700
2019-05-23 21:14:03.393 INFO   : zigbee: Frame Status: 0: SUCCESS
2019-05-23 21:14:03.400 INFO   : zigbee: Frame Status: 0: SUCCESS
[...]
```

I can sometimes control the Ikea light a few times before it stops responding:
```
[...]
2019-05-23 21:14:35.987 ERROR  : (node:851) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 propertyChanged listeners added. Use emitter.setMaxListeners() to increase limit
2019-05-23 21:14:55.829 INFO   : zigbee: setProperty property: on for: zb-0017880104857fbb-dimmableLight profileId: 0104 endpoint: 11 clusterId: 0006 zcl: off value: false
2019-05-23 21:14:58.545 INFO   : zigbee: setProperty property: on for: zb-0017880104857fbb-dimmableLight profileId: 0104 endpoint: 11 clusterId: 0006 zcl: on value: true
2019-05-23 21:15:01.164 INFO   : zigbee: setProperty property: on for: zb-0017880104857fbb-dimmableLight profileId: 0104 endpoint: 11 clusterId: 0006 zcl: on value: true
2019-05-23 21:15:03.072 INFO   : zigbee: setProperty property: on for: zb-000d6ffffe1a1f4a-onOffColorLight profileId: 0104 endpoint: 1 clusterId: 0006 zcl: off value: false
2019-05-23 21:15:05.854 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 21:15:05.971 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 21:15:09.888 INFO   : zigbee: setProperty property: on for: zb-000d6ffffead908b-multiLevelSwitch profileId: 0104 endpoint: 1 clusterId: 0006 zcl: off value: false
2019-05-23 21:15:17.882 INFO   : zigbee: setProperty property: on for: zb-000d6ffffead908b-multiLevelSwitch profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 21:15:25.866 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 21:15:25.986 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 21:15:26.097 INFO   : zigbee: setProperty property: on for: zb-000d6ffffe1a1f4a-onOffColorLight profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 21:15:26.144 INFO   : zigbee: setProperty property: on for: zb-000d6ffffead908b-multiLevelSwitch profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 21:15:26.193 INFO   : zigbee: setProperty property: on for: zb-000d6ffffe1a1f4a-onOffColorLight profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 21:15:45.881 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 21:15:45.990 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
```

Could that emitter.setMaxListeners() log entry be coming from zigbee-adapter (it might be entirely unrelated)?

**Comment by dhylands** [comment]
The MaxListeners is just a warning. It means that there are more than 11 listeners on a particular item, but is essntially benign

**Comment by svaarala** [comment]
I tried disabling/enabling the adapter, and looking at the logs (tailing $HOME/.mozilla-iot/log/run-app-xxx.log) it seems the adapter reloads but the same problems still persist. It detects the devices but fails to control any of them anymore (initially I was able to control a single light for a while but no longer).

Sometimes the enable/disable button freezes and the log shows that the adapter keeps on running. Maybe it cannot be disabled when a scan or some similar operation is ongoing?

**Comment by svaarala** [comment]
This is what happens when trying to control an Ikea Trådfri RGB light, which initially worked but now consistently fails:
```
[... Set RGB and ON from UI here ...]
2019-05-23 21:31:15.027 INFO   : zigbee: setProperty property: _level for: zb-000d6ffffe1a1f4a-onOffColorLight profileId: 0104 endpoint: 1 clusterId: 0008 zcl: level: 221 (87.1%) value: 87.05882352941177
2019-05-23 21:31:15.039 INFO   : zigbee: setProperty property: color for: zb-000d6ffffe1a1f4a-onOffColorLight profileId: 0104 endpoint: 1 clusterId: 0300 zcl: xyV: [0.202(13250), 0.237(15510),87.05882352941177] value: #21a1de
2019-05-23 21:31:20.795 INFO   : zigbee: setProperty property: on for: zb-000d6ffffe1a1f4a-onOffColorLight profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 21:31:22.304 INFO   : zigbee: setProperty property: on for: zb-000d6ffffe1a1f4a-onOffColorLight profileId: 0104 endpoint: 1 clusterId: 0006 zcl: on value: true
2019-05-23 21:31:25.052 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 21:31:25.166 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 21:31:45.075 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
2019-05-23 21:31:45.188 ERROR  : zigbee: Confirm Status: 208: ROUTE_DISCOVERY_FAILED
```

Does this mean the adapter is trying to set the logged properties, but there is no indication that the device actually received the messages?

**Comment by dhylands** [comment]
There is an initial scan period after the adapter is enabled where controlling things probably won't work. When the scan is finished you'll see something like the following printed in the log:
```
2019-05-23 13:44:25.491 INFO   : zigbee: ----- Nodes -----
2019-05-23 13:44:25.491 INFO   : zigbee: Node: 00212effff03d498 0000 Name: zb-00212effff03d498-Dongle       rebindRequired: true endpoints: []
2019-05-23 13:44:25.492 INFO   : zigbee:   Neighbor: d0cf5efffedcd23f 8d8d DT: Router R: Sibling  PJ: Y D:   1 LQI: 252
2019-05-23 13:44:25.492 INFO   : zigbee:   Neighbor: 000b57fffec49b71 022e DT: Router R: Sibling  PJ: Y D:   1 LQI: 255
2019-05-23 13:44:25.492 INFO   : zigbee: Node: 286d97000101a5ba 12f7 Name: zb-286d97000101a5ba-switch       rebindRequired: true endpoints: [ '1' ]
2019-05-23 13:44:25.492 INFO   : zigbee: Node: d0cf5efffedcd23f 8d8d Name: zb-d0cf5efffedcd23f-onOffSwitch  rebindRequired: true endpoints: [ '1', '2', '242' ]
2019-05-23 13:44:25.492 INFO   : zigbee: Node: 000b57fffec49b71 022e Name: zb-000b57fffec49b71-dimmableLigh rebindRequired: true endpoints: [ '1' ]
2019-05-23 13:44:25.492 INFO   : zigbee: -----------------
2019-05-23 13:44:25.492 INFO   : zigbee: ----- Update Network Addresses Complete -----
```

**Comment by dhylands** [comment]
Can you go into Settings->Addons and click on Configure for the zigbee adapter and enter `frames, frameDetail` into the debug field and click Apply. Then send me the log when you run into the device not responding. You can email to dhylands@mozilla.com

**Comment by dhylands** [comment]
I'd also like to point out that if you try to control a device which isn't on the network (typically a bulb that's been turned off or switch that's been unplugged) then the adapter will appear to be hung for about 30 seconds per command that was sent to the non-existent device. The adapter sends the packet out 3 times with a 10 second timeout, and other requests to other devices wind up getting queued up behind the packet for the non-existant device. This happens because there is only one queue for outgoing packets. I have in my todo list to add a queue per device which will resolve this particular problem, but that hasn't been implemented yet.

**Comment by manup** [comment]
Hi, I've noticed you're using an older firmware version for ConBee II.

>2019-05-23 21:14:03.384 INFO   : zigbee: DeConz Firmware version: 26420700

This firmware version has quite some issues with sleeping end-devices, like devices become unresponsive after some time. These problems were fixed in the current version 0x26490700.

To update the firmware deCONZ needs to be installed, the manual update is described here:

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Comment by svaarala** [comment]
Thanks, I'll update the stick.

**Comment by svaarala** [comment]
I've updated the firmware (I had to use the Windows deCONZ application, the firmware update was attempted but failed on Ubuntu or Debian). With this the zigbee-adapter log now shows:
```
2019-05-25 01:12:09.552 INFO   : zigbee: Rcvd: Version (0x0d) Response 26490700
```

The problems persist however. Based on the debug logs I sent to Dave there is Zigbee traffic to e.g. the light, and response traffic too, but the log shows "Wait NOT satisfied" and retries spaced 10 seconds apart. I'm unable to e.g. turn on/off the light at all, despite logs showing Zigbee basics do seem to work.

If it matters, all the devices I'm trying are mains powered (Philips Hue lights, Ikea Trådfri lights and on/off switch).

**Comment by dhylands** [comment]
I'm starting to see the dongle become non-responsive after sitting for a few hours. My original ConBee is rock solid and I use it every day for controlling lights and outlets and don't have any issues.

Once my Conbee II becomes non responsive I have to unplug and replug it and disable/enable the zigbee adapter to get things working again.

**Comment by manup** [comment]
Hmm strange this shouldn't happen. Is the zigbee-adapter setting the Watchdog TTL parameter periodically?
Otherwise the firmware will reboot roughly once per hour. For ConBee II this means the USB enumeration will be done again and application needs to reconnect. For ConBee I and RaspBee this isn't noticeable, since there is a FTDI in between and the USB device therefore doesn't re-enumerate when the firmware reboots.

I've updated the deCONZ Serial Protocol PDF to version 1.14. The Watchdog TTL parameter is now documented, this was previously only mentioned in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/158

**Comment by dhylands** [comment]
Ahhh. No the adapter isn't doing that. I will add that.

**Comment by sarimner** [comment]
Is there a way for a noob like me to fix this problem with the Conbee II stick?

**Comment by sarimner** [comment]
Should i use the zigbee adapter or the conbee zigbee addon in webthings to make it work?
Thankful for answer
//per

**Comment by dhylands** [comment]
The conbee adapter talks to the deCONZ reset server. So you can install the deCONZ REST server and use that adaptr. The regular zigbee adapter talks directly to the dongle.

**Comment by dhylands** [comment]
I just released version 0.7.8 of the zigbee adapter which should work better with the ConBee II

**Comment by sarimner** [comment]
Thank you for the update!
The Conbee II works much better now 👍

**Comment by svaarala** [comment]
Sorry to report that after updating to 0.7.10 my Conbee II still doesn't work :-/

**Comment by dhylands** [comment]
@svaarala Can you provide some error logs?
Is this running the standard gateway image?
Did you update the firmware on your ConBee II?

There are instructions for updating the firmware here:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Comment by svaarala** [comment]
The issue remains the same as described in my previous email. I can provide new error logs too if that's helpful.

I'm using the standard gateway image. I updated the ConBee II too, and the updated firmware version shows up in logs:
```
2019-05-25 01:12:09.552 INFO   : zigbee: Rcvd: Version (0x0d) Response 26490700
```

**Comment by Silvan85** [comment]
Hi I have same problem as was described at beginning of this issue.

According to WebThings Gateway I'm using zigbee-adapter in version 0.9.0 (newer then 0.7.10)
I'm using ConBee II firmware version 264A0700 so news and stil get:

`2019-09-13 21:05:26.903 INFO   : Loading add-on: zigbee-adapter
2019-09-13 21:05:27.427 INFO   : zigbee: Opening database: /home/node/.mozilla-iot/config/db.sqlite3
2019-09-13 21:05:27.458 INFO   : zigbee: Loading add-on for zigbee-adapter from /home/node/.mozilla-iot/addons/zigbee-adapter
2019-09-13 21:05:27.869 INFO   : zigbee: DEBUG config = 'frames, frameDetail'
2019-09-13 21:05:27.872 INFO   : zigbee: Enabling DEBUG_frames
2019-09-13 21:05:27.873 INFO   : zigbee: Enabling DEBUG_frameDetail
2019-09-13 21:05:28.295 ERROR  : zigbee: Error: Error: No such file or directory, cannot open /dev/ttyACM*
2019-09-13 21:05:28.297 INFO   : zigbee: Serial ports that were found:
2019-09-13 21:05:28.397 INFO   : zigbee: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE2118407 found @ /dev/ttyACM*
2019-09-13 21:05:28.398 ERROR  : zigbee: Failed to load zigbee-adapter - No Zigbee dongle found`

**Comment by dhylands** [comment]
This looks like a custom installation. The node serailport package uses udevadm to acquire a list of serial ports.

We've created a udevadm utility that is used on platforms (like OpenWRT) which produces compatible output to udevadm. It would be interesting to see the output from running the udevadm found in the /home/node/mozilla-iot/gateway/tools/udevadm

You should also make sure that the user running the gateway belongs to the dialout group.

The line:
```
USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE2118407 found @ /dev/ttyACM*
```
is quite suspicious. It should have the star at the end replaced by a number. What does `ls -l /dev/ttyACM*` show on your computer?

What computer/OS are you running this on?

**Comment by Silvan85** [comment]
Thank you for quick reply. 
I'm running docker image on Ubuntu 18.04.2 LTS (GNU/Linux 4.14.102-156 armv7l)
image source is image: mozillaiot/gateway:arm
root and my user are in dialout group .

/dev/ttyACM*  is also worrying me dongle is on /dev/ttyACM0

**Comment by Silvan85** [comment]
I was able to fix my problem.
Docker container has no access to dev/ttyACM0
I added 
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

To docker compose file and this allows zigbee-adapter to connect to my ConBee II

**Comment by khaydarov** [comment]
Hi there!
I have the same problem with Zigbee

2019-12-28 22:20:16.058 INFO   : zigbee: Serial ports that were found:
2019-12-28 22:20:16.307 INFO   : zigbee: Serial Device found @ /dev/ttyAMA0
2019-12-28 22:20:16.310 INFO   : zigbee: Serial Device found @ /dev/ttyS0
2019-12-28 22:20:16.313 INFO   : zigbee: USB Serial Device 0451:16a8 Vendor: Texas Instruments Serial: __0X00124B00194A0019 found @ /dev/ttyACM0
2019-12-28 22:20:16.315 ERROR  : zigbee: Failed to start add-on zigbee-adapter: No Zigbee dongle found

**Comment by mrstegeman** [comment]
@khaydarov Your dongle is not a Conbee. It's a CC2531, which we don't currently support.

**Comment by khaydarov** [comment]
@mrstegeman thanks for the response. Do you have a plan to support CC2531?

**Comment by mrstegeman** [comment]
@khaydarov see #101

**Comment by riccardocossu** [comment]
I am having a similiar problem with gateway version 0.10, after a move to a docker installation on a Ubuntu server 18.04 (x86); on the raspberry everything works fine, so the dongle itself is fine.
This is what I am getting

```
2020-01-02 07:44:52.303 INFO   : zigbee: Loading add-on zigbee-adapter from /home/node/.mozilla-iot/addons/zigbee-adapter
2020-01-02 07:44:52.365 INFO   : zigbee: DEBUG config = ''
2020-01-02 07:44:52.638 INFO   : zigbee: this.driver = DeconzDriver {}
2020-01-02 07:44:52.640 INFO   : zigbee: DeconzDriver: Using serial port /dev/ttyACM0
2020-01-02 07:44:58.658 INFO   : zigbee: Kicking WatchDog for 3600 seconds
2020-01-02 07:45:07.683 INFO   : zigbee:          MAC Address: undefined
2020-01-02 07:45:07.684 INFO   : zigbee:      Network PANID16: undefined
2020-01-02 07:45:07.686 INFO   : zigbee:       Network Addr16: undefined
2020-01-02 07:45:07.687 INFO   : zigbee:      Network PANID64: undefined
2020-01-02 07:45:07.688 INFO   : zigbee: APS Designated Coordinator: undefined
2020-01-02 07:45:07.692 ERROR  : zigbee: /home/node/.mozilla-iot/addons/zigbee-adapter/deconz-driver.js:386
2020-01-02 07:45:07.693 ERROR  : zigbee:         value = value.toString(16).padStart(8, '0');
2020-01-02 07:45:07.694 ERROR  : zigbee:                       ^
2020-01-02 07:45:07.694 ERROR  : zigbee: 
2020-01-02 07:45:07.695 ERROR  : zigbee: TypeError: Cannot read property 'toString' of undefined
2020-01-02 07:45:07.695 ERROR  : zigbee:     at DeconzDriver.dumpParameters (/home/node/.mozilla-iot/addons/zigbee-adapter/deconz-driver.js:386:23)
2020-01-02 07:45:07.696 ERROR  : zigbee:     at DeconzDriver.run (/home/node/.mozilla-iot/addons/zigbee-adapter/zb-driver.js:743:16)
2020-01-02 07:45:07.696 ERROR  : zigbee:     at DeconzDriver.waitTimedOut (/home/node/.mozilla-iot/addons/zigbee-adapter/zb-driver.js:807:14)
2020-01-02 07:45:07.697 ERROR  : zigbee:     at ontimeout (timers.js:498:11)
2020-01-02 07:45:07.697 ERROR  : zigbee:     at tryOnTimeout (timers.js:323:5)
2020-01-02 07:45:07.698 ERROR  : zigbee:     at Timer.listOnTimeout (timers.js:290:5)
2020-01-02 07:45:07.701 INFO   : Plugin: zigbee-adapter died, code = 1 restarting after 0
2020-01-02 07:45:08.148 INFO   : zigbee: Opening database: /home/node/.mozilla-iot/config/db.sqlite3
2020-01-02 07:45:08.672 INFO   : zigbee: Loading add-on zigbee-adapter from /home/node/.mozilla-iot/addons/zigbee-adapter
2020-01-02 07:45:08.734 INFO   : zigbee: DEBUG config = ''
2020-01-02 07:45:13.828 ERROR  : zigbee: SerialProber: timeout: deConz dongle not detected on /dev/ttyACM0
2020-01-02 07:45:13.830 INFO   : zigbee: Serial ports that were found:
2020-01-02 07:45:13.868 INFO   : zigbee: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: <serial> found @ /dev/ttyACM0
2020-01-02 07:45:13.870 ERROR  : zigbee: Failed to start add-on zigbee-adapter: No Zigbee dongle found
```

My docker-compose is like that:

```
version: "3"

services:
  webthings-gateway:
    container_name: webthings-gateway
    image: mozillaiot/gateway:latest
    restart: unless-stopped
    network_mode: host
    ports:
      - "9080:8080"
      - "4443:4443"
    volumes:
      - /home/riccardo/mozilla_gateway/config:/home/node/.mozilla-iot
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
```

And output from dmesg (everything looks fine there):

```
[54679.004100] usb 1-8: new full-speed USB device number 9 using xhci_hcd
[54679.153933] usb 1-8: New USB device found, idVendor=1cf1, idProduct=0030
[54679.153941] usb 1-8: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[54679.153945] usb 1-8: Product: ConBee II
[54679.153950] usb 1-8: Manufacturer: dresden elektronik ingenieurtechnik GmbH
[54679.153954] usb 1-8: SerialNumber: <same as the one showed in gateway logs>
[54679.156508] cdc_acm 1-8:1.0: ttyACM0: USB ACM device

```

**Comment by mrstegeman** [comment]
@riccardocossu I believe you mentioned on Discourse that you're now plugging into a USB 3 port. Out of curiosity, do you have a USB 2 hub available? I'm wondering if plugging your dongle into the hub would make things work better. We recently had a similar issue with a Z-Wave dongle.

**Comment by riccardocossu** [comment]
Thanks for the suggestion; I was actually wrong and I was using a USB2 port (but using a USB3 one doesn't work either). But your suggestion to use a hub worked at first try (for reference it's an Amazon basics 7 port powered USB2 hub)! No idea what's causing this weirdness, I never had any issue with those USB ports.
Thanks again for the help and the great work you're doing.

**Comment by kapn1966** [comment]
I am finding this problem intermittently using the gateway version .10 and zigbee version .10.8 (and the previous version as well). I am using the Raspberry Pi image on a RPi 3 with a ConBee 2 dongle. If I switch ports and reboot, the problem will usually clear itself. If I don't change the ports and simply reboot, the adapter still is usually not found. After the switch and reboot, it will work for a few days and then give up again.

**Comment by kapn1966** [comment]
And I seem to be back into unresponsive and the previous workaround doesn't work anymore. Maybe it only worked as long as I had a USB port I hadn't used yet. I've now used all 4 at some point.
I don't suppose anyone has an idea of a solution?

`2020-02-07 17:14:29.696 ERROR  : zigbee: SerialProber: timeout: deConz dongle not detected on /dev/ttyACM0
2020-02-07 17:14:29.698 INFO   : zigbee: Serial ports that were found:
2020-02-07 17:14:29.716 INFO   : zigbee: Unhandled Rejection
2020-02-07 17:14:29.718 ERROR  : zigbee: { Error: Canceled
2020-02-07 17:14:29.720 ERROR  : zigbee:     at Poller.emitCanceled (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/bindings/lib/poller.js:101:17)
2020-02-07 17:14:29.721 ERROR  : zigbee:     at Poller.stop (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/bindings/lib/poller.js:91:10)
2020-02-07 17:14:29.723 ERROR  : zigbee:     at close.then (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/bindings/lib/linux.js:48:19)
2020-02-07 17:14:29.725 ERROR  : zigbee:     at <anonymous> canceled: true }
2020-02-07 17:14:30.008 INFO   : zigbee: Serial Device found @ /dev/ttyAMA0
2020-02-07 17:14:30.009 INFO   : zigbee: Serial Device found @ /dev/ttyS0
2020-02-07 17:14:30.011 INFO   : zigbee: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE2126415 found @ /dev/ttyACM0
2020-02-07 17:14:30.013 ERROR  : zigbee: Failed to start add-on zigbee-adapter: No Zigbee dongle found`

**Comment by kapn1966** [comment]
Seems like the database gets locked up somehow. Not sure what is triggering that. I found a way to reset the db locks by making a copy and then rebooting. Really not fun. I guess this might be a gateway issue and not a zigbee adapter issue. Will shift the conversation over there.

**Comment by flatsiedatsie** [comment]
I have the same issue: `ERROR  : zigbee-adapter: Confirm Status: 208: ROUTE_DISCOVERY_FAILED addr: etcetcetc`

Latest gateway on a Pi 4.
I also have an arduino and a USB microphone plugged in. I'm not sure if it's related, but the Arduino may be related somehow. Perhaps USB port use/scans by the MySensors addon are interfering?

- Reboot doesn't seem to fix it.
- It may have started becoming unreliable after I once yanked the Conbee 2 from the USB port while the system was running.

**Comment by flatsiedatsie** [comment]
Deleting the add-on and reinstalling it helped. Moving the stick to another port didn't - it seemed to be keyed to the one it was plugged in initially. Other settings also seem to have been kept after the addon was deleted.

After this adventure one IKEA lamp will no longer connect, no matter what I try:

```
2020-04-03 21:46:06.353 ERROR  : zigbee-adapter: Confirm Status: 208: ROUTE_DISCOVERY_FAILED addr: 086bd7ffXXXXXXXX 082f
2020-04-03 21:46:06.477 ERROR  : zigbee-adapter: Confirm Status: 208: ROUTE_DISCOVERY_FAILED addr: 086bd7ffXXXXXXXX 082f
```

**Comment by Chipandcharge** [comment]
Hey all,

firstly, thanks for providing the software and the adapter. I currently ran into the same problem, that is described in the beginning of this issue. 

My setup:
Raspberry 4 running Webthings as a Docker container. Connbee 2 is connected, but the Adapter (Version 0.11) is not recogniozing the conbee 2 stick. 

Log:
gateway_1  | 2020-04-24 16:36:00.851 INFO   : Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/zigbee-adapter-0.11.0-linux-arm-v12.tgz as /tmp/P1NAq7/zigbee-adapter.tar.gz
gateway_1  | 2020-04-24 16:36:03.292 INFO   : Expanding add-on /tmp/P1NAq7/zigbee-adapter.tar.gz
gateway_1  | 2020-04-24 16:36:09.380 INFO   : Loading add-on: zigbee-adapter
gateway_1  | 2020-04-24 16:36:10.222 INFO   : zigbee-adapter: Opening database: /home/node/.mozilla-iot/config/db.sqlite3
gateway_1  | 2020-04-24 16:36:10.586 INFO   : zigbee-adapter: Loading add-on zigbee-adapter from /home/node/.mozilla-iot/addons/zigbee-adapter
gateway_1  | 2020-04-24 16:36:12.353 INFO   : zigbee-adapter: DEBUG config = ''
gateway_1  | 2020-04-24 16:36:12.484 ERROR  : zigbee-adapter: [Error: Error: No such file or directory, cannot open /dev/ttyACM*]
gateway_1  | 2020-04-24 16:36:12.486 INFO   : zigbee-adapter: Serial ports that were found:
gateway_1  | 2020-04-24 16:36:12.548 INFO   : zigbee-adapter: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE2196055 found @ /dev/ttyACM*
gateway_1  | 2020-04-24 16:36:12.550 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyAMA*
gateway_1  | 2020-04-24 16:36:12.551 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found

Is there anything I need to configer in the docker container?
Thanks for your help. :)

**Comment by mrstegeman** [comment]
@Chipandcharge see the "Notes" section of the Docker README: https://github.com/mozilla-iot/gateway-docker/blob/master/README.md#notes

For instance, on my machine, I have to use a udev rule on the host to give the device node the proper permissions, such that it is readable inside the Docker container.

**Comment by Chipandcharge** [comment]
@mrstegeman Thnaks for the blizzardly fast reply and the perfect hint. I extended the docker-compose fiel with a device, and `sudo usermod -a -G dialout $USER` helped me to solve the dialout issue. 
Any udev rule is not neccessary in my case. Have a nice evening.

**Comment by joris-** [comment]
I've still this error : 
`Failed to start add-on Zigbee: No Zigbee dongle found`

I'm using RPI 4B with Conbee II on a fresh install

When I disable and enable Zigbee adapter I got this log output : 

```
2020-04-26 11:48:06.060 INFO   : Loading add-on: zigbee-adapter
2020-04-26 11:48:06.999 INFO   : zigbee-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-04-26 11:48:07.427 INFO   : zigbee-adapter: Loading add-on zigbee-adapter from /home/pi/.mozilla-iot/addons/zigbee-adapter
2020-04-26 11:48:07.477 INFO   : zigbee-adapter: DEBUG config = ''
2020-04-26 11:48:08.193 ERROR  : zigbee-adapter: events.js:174
2020-04-26 11:48:08.194 ERROR  : zigbee-adapter:       throw er; // Unhandled 'error' event
2020-04-26 11:48:08.195 ERROR  : zigbee-adapter:       ^
2020-04-26 11:48:08.196 ERROR  : zigbee-adapter: 
2020-04-26 11:48:08.197 ERROR  : zigbee-adapter: Error: Port is not open
2020-04-26 11:48:08.198 ERROR  : zigbee-adapter:     at SerialPort.close (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/stream/stream.js:425:29)
2020-04-26 11:48:08.199 ERROR  : zigbee-adapter:     at Timeout.setTimeout [as _onTimeout] (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/serial-prober/serial-prober.js:91:20)
2020-04-26 11:48:08.200 ERROR  : zigbee-adapter:     at ontimeout (timers.js:436:11)
2020-04-26 11:48:08.201 ERROR  : zigbee-adapter:     at tryOnTimeout (timers.js:300:5)
2020-04-26 11:48:08.202 ERROR  : zigbee-adapter:     at listOnTimeout (timers.js:263:5)
2020-04-26 11:48:08.203 ERROR  : zigbee-adapter:     at Timer.processTimers (timers.js:223:10)
2020-04-26 11:48:08.204 ERROR  : zigbee-adapter: Emitted 'error' event at:
2020-04-26 11:48:08.205 ERROR  : zigbee-adapter:     at SerialPort._error (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/stream/stream.js:199:10)
2020-04-26 11:48:08.206 ERROR  : zigbee-adapter:     at process.nextTick (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/@serialport/stream/stream.js:204:31)
2020-04-26 11:48:08.207 ERROR  : zigbee-adapter:     at process._tickCallback (internal/process/next_tick.js:61:11)
2020-04-26 11:48:08.209 INFO   : Plugin: zigbee-adapter died, code = 1 restarting after 0
2020-04-26 11:48:09.132 INFO   : zigbee-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-04-26 11:48:09.542 INFO   : zigbee-adapter: Loading add-on zigbee-adapter from /home/pi/.mozilla-iot/addons/zigbee-adapter
2020-04-26 11:48:09.598 INFO   : zigbee-adapter: DEBUG config = ''
2020-04-26 11:48:09.793 INFO   : zigbee-adapter: Serial ports that were found:
2020-04-26 11:48:09.930 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyAMA0
2020-04-26 11:48:09.932 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS0
2020-04-26 11:48:09.934 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found
```

**Comment by riccardocossu** [comment]
I have had issues with my dongle when connected directly to the host; I only made it work by connecting it to a USB2 hub; I had a similar log, the adapter was found but failed to initialize

**Comment by mrstegeman** [comment]
This dongle is fully supported. Please open new issues for problems with it.
